sudo: required

services:
  - docker
  - docker-compose

before_install:
  - docker-compose -f docker-compose-bind.yml build
  - docker-compose up -d
  - docker ps -a

script:
  - bundle exec rake test
